stages:
  - build
  - deploy

build_image_prod:
  stage: build
  script:
    - ssh $USER@$HOSTNAME 'make react_admin_build BRANCH=main'
  only:
    - main

deploy_to_prod:
  stage: deploy
  script:
    - ssh $USER@$HOSTNAME 'make react_admin_deploy BRANCH=main'
  only:
    - main